version: '3.8'

services:
  db:
    image: mysql:5.6
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timesheet
    volumes:
      - mysql_data:/var/lib/mysql

  spring_app:
    image: sofienmeddeb278/projetdevops
    restart: on-failure
    ports:
      - "8086:8086"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/foyer?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DIALECT: org.hibernate.dialect.MySQL5Dialect



volumes:
  mysql_data:
