version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: foyer
    volumes:
      - mysql_data:/var/lib/mysql
    

  app-timesheet:
    image: talbighofrane/foyer:1.0.0
    restart: on-failure
    ports:
      - "8086:8086"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/foyer?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect

  front-end:
    image: talbighofrane/front
    ports:
      - '4200:4200'
    networks:
      - backnetwork

networks:
  backnetwork:

volumes:
  mysql_data:
