version: "3.7"
services:
  spring_app:
    image: sofienmeddeb278/projetdevops
    container_name: Kaddem
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql:3306/foyer?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped

    depends_on:
      - dbmysql

  dbmysql:
    image: "mysql:8.1.0"
    container_name: dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql



volumes:
  db: