version: "3.7"
services:
  spring_app:
    image: sofienmeddeb278/projetdevopsval
    container_name: spring_app
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbmysql:3306/foyer?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped
    depends_on:
      - dbmysql
    networks:
      - my-network

  dbmysql:
    image: "mysql:8.1.0"
    container_name: dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-network

  front:
    image: sofienmeddeb278/projetdevopsfront:latest
    ports:
      - "4200:4200"
    restart: always
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db:
