version: '3'

services:
  db:
    container_name: db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: arwa
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: projetspring
    networks:
      - backnetwork
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8084:80"
    networks:
      - backnetwork

  spring-boot-container:
    image: arwabougattaya180/my-foyer-image
    ports:
      - '8086:8086'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/projetspring
      SPRING_DATASOURCE_USERNAME: arwa
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backnetwork

  front-end:
      image: arwabougattaya180/my-front-image
      ports:
        - '4200:4200'
      networks:
        - backnetwork

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    networks:
      - backnetwork

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      ports:
        - "9091:9090"
      volumes:
        - prometheus_data:/prometheus
        - ./prometheus.yml:/etc/prometheus/prometheus.yml

      restart: always
      networks:
        - backnetwork



networks:
  backnetwork:

volumes:
  mysql_data:
  grafana_data:
  prometheus_data:
