version: '3'

services:
  db:
    container_name: db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: projetspring
    networks:
      - backnetwork
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8084:80"
    networks:
      - backnetwork

  spring-boot-container:
    image: emna698/foyer-image
    ports:
      - '8086:8086'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/projetspring?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backnetwork

  front-end:
    image: emna698/front-images
    ports:
      - '4200:4200'
    networks:
      - backnetwork

networks:
  backnetwork:

volumes:
  mysql_data:
